# Set OS to linux
os: linux

# Set the build language to Python
language: python

# Set the python version to 3.5
python: 3.5

before_install:
  - sudo apt-get update

# Install the library dependcies
install:
  - sudo apt-get install python3
  - pip3 install numpy opencv-python

# Run python scripts
script:
  - cd Code/
  - python3 detector.py
  - python3 superimpose.py
  - python3 draw_3d.py
  - python3 main.py videos/multipleTag.mp4 videos/demo.avi